<?
	session_start();
	$user = $_SESSION['sid'];
	include("connect_db.php");
	include("db_name.php");

?>

<head>
	<meta http-equiv="Content-Type" content"text/html; charset="Big5"/>
	<style>
	
		#main 
		{
			width: 100%;
			height: 95%;
			border: 0px;
		}
		
		#FloatDiv
		{
			width: 200px;
			height: 50px;
			position: fixed;
			bottom: 5px;
			right: 5px;
			background-color: #FFFFEE;
			border: 2px solid #AAFFAA;
			border-radius: 10px;
			box-shadow: 5px 5px 5px #888888;
			margin: 3px;
			padding: 2px;
			filter:alpha(opacity=70); opacity:0.7; zoom:1;
		
		}
		
		#FloatDiv:hover
		{
			filter:alpha(opacity=90); opacity:0.9; zoom:1.2;
		
		}
		
		
		.GoMain {
			position: relative;
			left: 60%;
			font-size:10px;
			font-family:Verdana;
			font-weight:normal;
			-moz-border-radius:8px;
			-webkit-border-radius:8px;
			border-radius:8px;
			border:0px solid #dbdbdb;
			padding:5px 10px;
			text-decoration:none;
			background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #f0edf0), color-stop(100%, #d1d1d1) );
			background:-moz-linear-gradient( center top, #f0edf0 5%, #d1d1d1 100% );
			background:-ms-linear-gradient( top, #f0edf0 5%, #d1d1d1 100% );
			filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#f0edf0', endColorstr='#d1d1d1');
			background-color:#f0edf0;
			color:#666666;
			display:inline-block;
			-webkit-box-shadow: 1px 0px 0px 0px #ffffff;
			-moz-box-shadow: 1px 0px 0px 0px #ffffff;
			box-shadow: 1px 0px 0px 0px #ffffff;
		}.GoMain:hover {
			background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #d1d1d1), color-stop(100%, #f0edf0) );
			background:-moz-linear-gradient( center top, #d1d1d1 5%, #f0edf0 100% );
			background:-ms-linear-gradient( top, #d1d1d1 5%, #f0edf0 100% );
			filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#d1d1d1', endColorstr='#f0edf0');
			background-color:#d1d1d1;
		}.GoMain:active {
			position:relative;
			top:1px;
		}
		/* This css button was generated by css-button-generator.com */
		
		#IDword 
		{
			padding: 3px 3px;
			color: #005300;
			
		
		}

				
	</style>
	<script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
	<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
	<script src="jquery.hotkeys.js"></script>
	<script>
	
		function GoMain(){
		
			$("#main").attr({src:"menu.php"});
		
		}
		$(document).bind('keydown','alt+b',function(evt){
		
			GoMain();
					
		});		
		$(document).ready(function(){
			HotKeyGo = function(){
					GoMain();
			}
		})
			
	
	</script>
</head>

<body>

	<iframe src="menu.php" id="main"></iframe>
	<div id="FloatDiv">
		<div id="IDword"><? echo $user;?>準備開始囉!</div>
		<a class="GoMain" onclick="GoMain();" href="#">回首頁(b)</a>
	</div>

</body>

</html>